# Generated by Django 4.2.4 on 2024-03-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, unique=True, verbose_name='user_name')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('uuid', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('last_login_ip', models.CharField(max_length=18, verbose_name='ip')),
                ('last_login_time', models.CharField(max_length=15, verbose_name='last_login_time')),
            ],
        ),
    ]
