# Generated by Django 4.2.4 on 2024-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_user_register_time_alter_user_last_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@domain.com', max_length=50, verbose_name='email'),
        ),
    ]
